asttokens==2.1.0
backcall==0.2.0
certifi==2022.9.24
cffi @ file:///tmp/abs_98z5h56wf8/croots/recipe/cffi_1659598650955/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
contourpy==1.0.6
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
entrypoints==0.4
executing==1.2.0
fonttools==4.38.0
future @ file:///home/conda/feedstock_root/build_artifacts/future_1666786049710/work
ipykernel==6.16.2
ipython==8.6.0
jedi==0.18.1
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1663332044897/work
jupyter_client==7.4.4
jupyter_core==4.11.2
kiwisolver==1.4.4
matplotlib==3.6.1
matplotlib-inline==0.1.6
mkl-fft==1.3.1
mkl-random==1.2.2
mkl-service==2.4.0
nest-asyncio==1.5.6
numpy @ file:///croot/numpy_and_numpy_base_1665773175172/work
packaging==21.3
pandas==1.5.1
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.3.0
prompt-toolkit==3.0.31
psutil==5.9.3
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytorch-tabnet @ file:///home/conda/feedstock_root/build_artifacts/pytorch-tabnet_1640894519501/work
pytz==2022.5
pyzmq==24.0.1
scikit-learn @ file:///croot/scikit-learn_1665482011620/work
scipy==1.9.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
stack-data==0.6.0
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
torch==1.10.2
tornado==6.2
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1662214488106/work
traitlets==5.5.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1665144421445/work
wcwidth==0.2.5
